modLoader = "javafml"
loaderVersion = "[2,)"
license = "GPL-3.0-only"

[[mods]]
modId = "exposuregrading"
version = "1.0.0"
displayName = "Exposure Grading"
description = '''
A Minecraft mod for Exposure Grading
'''

[[dependencies.exposuregrading]]
modId = "neoforge"
required = true
versionRange = "[21,)"

[[dependencies.exposuregrading]]
modId = "minecraft"
required = true
versionRange = "[1.21.1,1.21.2)"
