modLoader = "javafml"
loaderVersion = "[2,)"
license = "GPL-3.0-only"

[[mods]]
modId = "exposure_grading"
version = "1.0.0"
displayName = "Exposure: Grading"
description = '''
A Minecraft mod for Exposure Grading
'''

[[dependencies.exposure_grading]]
modId = "neoforge"
required = true
versionRange = "[21,)"

[[dependencies.exposure_grading]]
modId = "minecraft"
required = true
versionRange = "[1.21.1,1.21.2)"

[[dependencies.exposure_grading]]
modId = "exposure"
required = true
versionRange = "[1.9,)"

[[dependencies.exposure_grading]]
modId = "exposure_polaroid"
required = false

[[dependencies.exposure_grading]]
modId = "exposure_expanded"
required = false
